# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Variant(models.Model):
    Chromosome_Number = models.BigIntegerField(default=0)
    Position = models.CharField(max_length=1000, default="")
    Var_ID = models.CharField(max_length=1000, default="")
    Reference = models.CharField(max_length=1000, default="")
    Alternate = models.CharField(max_length=1000, default="")
    Quality = models.CharField(max_length=1000, default="")
    Filter =models.CharField(max_length=1000, default="")
    Info = models.CharField(max_length=1000, default="")

class Annotation(models.Model):
    Variant = models.ForeignKey( Variant, on_delete=models.CASCADE)
    Allele = models.CharField(max_length=1000, default="")
    Consequence = models.CharField(max_length=1000, default="")
    Impact = models.CharField(max_length=1000, default="")
    Gene_Symbol = models.CharField(max_length=1000, default="")
    Gene = models.CharField(max_length=1000, default="")
    Feature = models.CharField(max_length=1000, default="")
    Feature_type = models.CharField(max_length=1000, default="")
    Biotype = models.CharField(max_length=1000, default="")
    Exon = models.CharField(max_length=1000, default="")
    Intron = models.CharField(max_length=1000, default="")
    HGVS_DNA = models.CharField(max_length=1000, default="")
    HGVS_Protein = models.CharField(max_length=1000, default="")
    cDNA_position = models.CharField(max_length=1000, default="")
    CDS_position = models.CharField(max_length=1000, default="")
    Protein_position = models.CharField(max_length=1000, default="")
    Amino_acids = models.CharField(max_length=1000, default="")
    Codons = models.CharField(max_length=1000, default="")
    Existing_variation = models.CharField(max_length=1000, default="")
    ALLELE_NUM = models.CharField(max_length=1000, default="")
    DISTANCE = models.CharField(max_length=1000, default="")
    STRAND = models.CharField(max_length=1000, default="")
    VARIANT_CLASS = models.CharField(max_length=1000, default="")
    MINIMISED = models.CharField(max_length=1000, default="")
    SYMBOL_SOURCE = models.CharField(max_length=1000, default="")
    HGNC_ID = models.CharField(max_length=1000, default="")
    CANONICAL = models.CharField(max_length=1000, default="")
    TSL = models.CharField(max_length=1000, default="")
    CCDS = models.CharField(max_length=1000, default="")
    ENSP = models.CharField(max_length=1000, default="")
    SWISSPROT = models.CharField(max_length=1000, default="")
    TREMBL = models.CharField(max_length=1000, default="")
    UNIPARC = models.CharField(max_length=1000, default="")
    SIFT = models.CharField(max_length=1000, default="")
    PolyPhen = models.CharField(max_length=1000, default="")
    DOMAINS = models.CharField(max_length=1000, default="")
    HGVS_OFFSET = models.CharField(max_length=1000, default="")
    GMAF = models.CharField(max_length=1000, default="")
    AFR_MAF = models.CharField(max_length=1000, default="")
    AMR_MAF = models.CharField(max_length=1000, default="")
    ASN_MAF = models.CharField(max_length=1000, default="")
    EAS_MAF = models.CharField(max_length=1000, default="")
    EUR_MAF = models.CharField(max_length=1000, default="")
    SAS_MAF = models.CharField(max_length=1000, default="")
    AA_MAF = models.CharField(max_length=1000, default="")
    EA_MAF = models.CharField(max_length=1000, default="")
    CLIN_SIG = models.CharField(max_length=1000, default="")
    SOMATIC = models.CharField(max_length=1000, default="")
    PHENO = models.CharField(max_length=1000, default="")
    PUBMED = models.CharField(max_length=1000, default="")
    MOTIF_NAME = models.CharField(max_length=1000, default="")
    MOTIF_POS = models.CharField(max_length=1000, default="")
    HIGH_INF_POS = models.CharField(max_length=1000, default="")
    MOTIF_SCORE_CHANGE = models.CharField(max_length=1000, default="")
    LoF_info = models.CharField(max_length=1000, default="")
    LoF_flags = models.CharField(max_length=1000, default="")
    LoF_filter = models.CharField(max_length=1000, default="")
    LoF = models.CharField(max_length=1000, default="")
    context = models.CharField(max_length=1000, default="")
    ancestral = models.CharField(max_length=1000, default="")


class Population(models.Model):
    Variant = models.ForeignKey(Variant, on_delete=models.CASCADE)
    Allele_Count=models.CharField(max_length=1000, default="")
    AC_African_American=models.CharField(max_length=1000, default="")
    AC_American=models.CharField(max_length=1000, default="")
    AC_Adjusted=models.CharField(max_length=1000, default="")
    AC_East_Asian=models.CharField(max_length=1000, default="")
    AC_Finnish=models.CharField(max_length=1000, default="")
    AC_Hemizygous=models.CharField(max_length=1000, default="")
    AC_Heterozygous=models.CharField(max_length=1000, default="")
    AC_Homozygous=models.CharField(max_length=1000, default="")
    AC_Non_Finnish_European=models.CharField(max_length=1000, default="")
    AC_Other=models.CharField(max_length=1000, default="")
    AC_South_Asian=models.CharField(max_length=1000, default="")
    Allele_Frequency=models.FloatField(max_length=1000, default="")
    Allele_Number=models.CharField(max_length=1000, default="")
    AN_African_American=models.CharField(max_length=1000, default="")
    AN_American=models.CharField(max_length=1000, default="")
    AN_Adjusted=models.CharField(max_length=1000, default="")
    AN_East_Asian=models.CharField(max_length=1000, default="")
    AN_Finnish=models.CharField(max_length=1000, default="")
    AN_Non_Finnish=models.CharField(max_length=1000, default="")
    AN_Other=models.CharField(max_length=1000, default="")
    AN_South_Asian=models.CharField(max_length=1000, default="")
    Read_Depth=models.CharField(max_length=1000, default="")
    Genotype_Quality_MEAN=models.CharField(max_length=1000, default="")
    GQ_Standard_Deviation=models.FloatField(max_length=1000, default="")
    Hemi_African_American=models.CharField(max_length=1000, default="")
    Hemi_American=models.CharField(max_length=1000, default="")
    Hemi_East_Asian=models.CharField(max_length=1000, default="")
    Hemi_Finnish=models.CharField(max_length=1000, default="")
    Hemi_Non_Finnish_European=models.CharField(max_length=1000, default="")
    Hemi_Other=models.CharField(max_length=1000, default="")
    Hemi_South_Asian=models.CharField(max_length=1000, default="")
    Het_African_American=models.CharField(max_length=1000, default="")
    Het_American=models.CharField(max_length=1000, default="")
    Het_East_Asian=models.CharField(max_length=1000, default="")
    Het_Finnish=models.CharField(max_length=1000, default="")
    Het_Non_Finnish_European=models.CharField(max_length=1000, default="")
    Het_Other=models.CharField(max_length=1000, default="")
    Het_South_Asian=models.CharField(max_length=1000, default="")
    Hom_African_American=models.CharField(max_length=1000, default="")
    Hom_American=models.CharField(max_length=1000, default="")
    Hom_East_Asian=models.CharField(max_length=1000, default="")
    Hom_Finnish=models.CharField(max_length=1000, default="")
    Hom_Non_Finnish_European_Homozygous=models.CharField(max_length=1000, default="")
    Hom_Other=models.CharField(max_length=1000, default="")
    Hom_South_Asian=models.CharField(max_length=1000, default="")
    InbreedingCoef=models.CharField(max_length=1000, default="")
    DP_HIST=models.CharField(max_length=1000, default="")
    GQ_HIST=models.CharField(max_length=1000, default="")